version: '3.4'

services:
  nginx:
    build: .
    ports:
      - ${SOAPBOX_PORT}:3000
    volumes:
      # - ./setting/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/templates:/etc/nginx/templates:ro
    environment:
      SOAPBOX_HOSTNAME: ${SOAPBOX_HOSTNAME}
      PLEROMA_HOSTNAME: ${PLEROMA_HOSTNAME}
    networks:
      - caddy
    labels:
      caddy: ${SOAPBOX_HOSTNAME}
      caddy.reverse_proxy: "nginx:${SOAPBOX_PORT}"

networks:
  caddy:
    external: true
