version: '3.4'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./setting/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./setting/nginx/templates:/etc/nginx/templates
    environment:
      SOAPBOX_HOSTNAME: ${SOAPBOX_HOSTNAME}
      PLEROMA_HOSTNAME: ${PLEROMA_HOSTNAME}
    labels:
      caddy: ${SOAPBOX_HOSTNAME}
      caddy.reverse_proxy: "nginx:80"