version: '3.4'

services:
  nginx:
    build: .
    expose:
      - ${SOAPBOX_PORT}
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/templates:/etc/nginx/templates:ro
    environment:
      VIRTUAL_HOST: ${SOAPBOX_HOSTNAME}
      VIRTUAL_PORT: ${SOAPBOX_PORT}
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: ${SOAPBOX_HOSTNAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_TEST: "false"
    networks:
      - front

networks:
  front:
    external: true
