version: '3.4'

services:
  nginx:
    build: .
    ports:
      - 80:80
    volumes:
      - ./setting/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./setting/nginx/templates:/etc/nginx/templates
    environment:
      SOAPBOX_HOSTNAME: ${SOAPBOX_HOSTNAME}
      SOAPBOX_PORT: ${SOAPBOX_PORT}
      PLEROMA_HOSTNAME: ${PLEROMA_HOSTNAME}
    networks:
      - caddy
    labels:
      caddy: ${SOAPBOX_HOSTNAME}
      caddy.reverse_proxy: "nginx:${SOAPBOX_PORT}"

networks:
  caddy:
    external: true
