version: '3.4'

services:
  nginx:
    build: .
    ports:
      - ${SOAPBOX_PORT}:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/templates:/etc/nginx/templates:ro
    environment:
      SOAPBOX_HOSTNAME: ${SOAPBOX_HOSTNAME}
      PLEROMA_HOSTNAME: ${PLEROMA_HOSTNAME}
    networks:
      - caddy
    labels:
      caddy: ${SOAPBOX_HOSTNAME}
      caddy.reverse_proxy: nginx:${SOAPBOX_PORT}

networks:
  caddy:
    external: true
