name: Soapbox Build

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/cache@v3
        id: cache
        with:
          path: soapbox/node-modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('soapbox/yarn.lock') }}-${{ hashFiles('soapbox/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd soapbox && yarn
      # - name: yarn build
      #   run: cd soapbox && yarn build
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: soapbox-fe
          path: soapbox/static
