name: Soapbox Build

on:
  push:
    branches:
      - master

env:
  NODE_ENV: ${{ vars.NODE_ENV }}
  BACKEND_URL: ${{ vars.BACKEND_URL }}
  PROXY_HTTPS_INSECURE: ${{ vars.PROXY_HTTPS_INSECURE }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: soapbox/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('soapbox/yarn.lock') }}-${{ hashFiles('soapbox/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: cd soapbox && yarn
      - name: build
        run: | 
          cd soapbox
          echo "NODE_ENV=${{ env.NODE_ENV }}" >> .env
          echo "BACKEND_URL=${{ env.BACKEND_URL }}" >> .env
          echo "PROXY_HTTPS_INSECURE=${{ env.PROXY_HTTPS_INSECURE }}" >> .env
          yarn build
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: soapbox-fe
          path: soapbox/static
