name: Soapbox Build

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: soapbox/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('soapbox/yarn.lock') }}-${{ hashFiles('soapbox/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: cd soapbox && yarn

      - name: build soapbox.wakuwakup.net
        run: cd soapbox && yarn build
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          BACKEND_URL: ${{ secrets.BACKEND_URL_WAKUWAKUP_NET }}
          PROXY_HTTPS_INSECURE: ${{ secrets.PROXY_HTTPS_INSECURE }}

      - name: Upload artifact soapbox.wakuwakup.net
        uses: actions/upload-artifact@v2
        with:
          name: soapbox-fe-wakuwakup-net
          path: soapbox/static

      - name: build sb.nagi.fan
        run: cd soapbox && yarn build
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          BACKEND_URL: ${{ secrets.BACKEND_URL_NAGI_FAN }}
          PROXY_HTTPS_INSECURE: ${{ secrets.PROXY_HTTPS_INSECURE }}

      - name: Upload artifact soapbox.wakuwakup.net
        uses: actions/upload-artifact@v2
        with:
          name: soapbox-fe-nagi-fan
          path: soapbox/static
